# Generated by Django 4.2.4 on 2023-09-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="arrival_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
