# Generated by Django 4.2.4 on 2023-09-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journies", "0004_alter_journey_trip_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="distance",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
