# Generated by Django 4.2.4 on 2023-08-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrainType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "services",
                    models.CharField(
                        choices=[
                            ("air-conditioning", "Air Conditioning"),
                            ("WC", "Wc"),
                            ("bistro carriage", "Bistro Carriage"),
                            ("WIFI", "Wifi"),
                            ("230V electrical sockets", "Sockets"),
                            (
                                "audio and visual information system",
                                "Information System",
                            ),
                            ("a in-seat refreshment service", "Refreshment Service"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cargo_num", models.IntegerField()),
                ("places_in_cargo", models.IntegerField()),
                (
                    "train_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trains.traintype",
                    ),
                ),
            ],
        ),
    ]
