# Generated by Django 4.2.4 on 2023-08-28 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="train",
            name="train_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="train",
                to="trains.traintype",
            ),
        ),
        migrations.AlterField(
            model_name="traintype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name="traintype",
            name="services",
        ),
        migrations.AddField(
            model_name="traintype",
            name="services",
            field=models.ManyToManyField(
                related_name="train_type", to="trains.services"
            ),
        ),
    ]
