# Generated by Django 4.2.4 on 2023-08-28 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "trains",
            "0002_services_alter_train_train_type_alter_traintype_name_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Services",
            new_name="Service",
        ),
    ]
