# Generated by Django 4.2.4 on 2023-09-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0003_rename_services_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="traintype",
            name="max_speed",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
