# Generated by Django 4.2.4 on 2023-09-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="stop_station",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="route", to="routes.station"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="stop_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="route",
            name="distance",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
