# Generated by Django 4.2.4 on 2023-09-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0002_route_stop_station_station_stop_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="stop_station",
            field=models.ManyToManyField(
                blank=True, related_name="route", to="routes.station"
            ),
        ),
    ]
