# Generated by Django 4.2.4 on 2023-09-06 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0002_alter_route_distance"),
        ("routes", "0003_alter_route_stop_station"),
    ]

    operations = []
